# Generated by Django 3.2.5 on 2021-08-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(blank=True, max_length=200, null=True)),
                ('club_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('club_img_url', models.CharField(blank=True, max_length=500, null=True)),
                ('club_logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('established', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('end_day', models.DateTimeField()),
                ('deadline', models.IntegerField()),
                ('sns_link', models.CharField(blank=True, max_length=500, null=True)),
                ('form_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubTypes',
            fields=[
                ('club_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_type_name', models.IntegerField(blank=True, null=True)),
                ('club_type_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('club_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'club_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.CharField(max_length=3000)),
                ('post_introduce', models.CharField(blank=True, max_length=200, null=True)),
                ('post_img_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruitment_content', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'recruitment',
                'managed': False,
            },
        ),
    ]
