# Generated by Django 3.2.5 on 2021-08-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='recruitment_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Recruitment',
        ),
    ]
