# Generated by Django 3.2.3 on 2021-08-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clubs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clubtypes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={},
        ),
    ]
