# Generated by Django 3.1.2 on 2021-08-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_img_url',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_content',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
