# Generated by Django 3.1.2 on 2021-08-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210821_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_introduce',
        ),
    ]
