# Generated by Django 3.1.2 on 2021-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210813_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='club_img_url',
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='main_club',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
