# Generated by Django 3.1.2 on 2021-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210814_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
